### ISSUE TITLE
Mandatory delay before each I2C I/O

### ISSUE THREAD

**Issue by MarkoSagadin** [blues/note-c#82]
Hello!

We are using note-c as a base for our internal Zephyr Notecard driver.

I want to know this: is it mandatory to add a delay before every I2C transmit and receive operation?

I have set to use the turbo mode all the time on our hardware. This makes I2C communication unreliable, sometimes it works as it should, sometimes the Notecard does not give back no response.

Below is a example of I2C communication (click image to enlarge) after issuing `{"req":"card.temp"}` request, the Notecard always responds that it has nothing to say back.

![image](https://github.com/blues/note-c/assets/41839945/d3760215-a2cb-488d-9cd0-ff33ded60d70)

The I2C write and read operations are happening with 80 us pauses.

There are two ways that solve this (for me):
* Disable turbo mode (but this adds 250 ms and 20 ms delays between segments and chunks respectively).
* Add 1 ms delay before every I2C I/O (essentially remove if statement in `_DelayIO()`, and change 6 to 1). 

First option is not an option for me as I want to minimize time when sending large payloads via `web.post`.
I can add 1ms delay in my driver implementation.

However, is 1 ms delay something that should be default, as even the [Blues Docs](https://dev.blues.io/guides-and-tutorials/notecard-guides/serial-over-i2c-protocol/#data-query) mention that there should be a minimum 1 ms delay between transactions?

**Comment by MarkoSagadin** [comment]
Hello @haydenroche5, thank you for the detailed answer. Yes, when I saw that you could enable/disable turbo mode really made me question, what is the correct setting.

Thank you for clarifying this.

**Comment by haydenroche5** [comment]
Happy to help. :)
